export const districts = ["玄武区", "秦淮区", "建邺区", "鼓楼区", "浦口区", "栖霞区", "雨花台区", "江宁区", "六合区", "溧水区", "高淳区"];

export const districtLabels: Record<string, string> = {
    "玄武区": "Xuanwu District",
    "秦淮区": "Qinhuai District",
    "建邺区": "Jianye District",
    "鼓楼区": "Gulou District",
    "浦口区": "Pukou District",
    "栖霞区": "Qixia District",
    "雨花台区": "Yuhuatai District",
    "江宁区": "Jiangning District",
    "六合区": "Luhe District",
    "溧水区": "Lishui District",
    "高淳区": "Gaochun District"
};

export const poiCategories = ["餐饮", "风景名胜", "公共设施", "交通设施服务", "公司企业", "购物", "金融保险服务", "科教文化服务", "商务住宅", "生活服务", "体育休闲服务", "医疗保健服务", "政府机构及社会团体", "住宿服务"];

export const poiCategoryLabels: Record<string, string> = {
    "餐饮": "Food & Dining",
    "风景名胜": "Scenic Spots",
    "公共设施": "Public Facilities",
    "交通设施服务": "Transport Facilities",
    "公司企业": "Companies & Enterprises",
    "购物": "Shopping",
    "金融保险服务": "Finance & Insurance",
    "科教文化服务": "Science, Education & Culture",
    "商务住宅": "Business & Residential",
    "生活服务": "Daily Services",
    "体育休闲服务": "Sports & Leisure",
    "医疗保健服务": "Healthcare",
    "政府机构及社会团体": "Government & Organizations",
    "住宿服务": "Accommodation"
};

export const poiSubcategoriesByCategory: Record<string, string[]> = {
    "餐饮": ["中餐厅", "快餐厅", "外国餐厅", "休闲餐饮场所", "宾馆酒店", "娱乐场所", "糕饼店", "咖啡厅", "休闲场所", "茶艺馆", "冷饮店", "综合市场", "旅馆招待所", "美容美发店", "甜品店", "楼宇", "服装鞋帽皮具店", "度假疗养场所", "风景名胜", "运动场馆"],
    "风景名胜": ["风景名胜", "公园广场", "风景名胜相关", "休闲场所", "度假疗养场所", "普通地名", "住宅区", "中餐厅", "运动场馆", "科教文化场所", "科技馆", "社会团体", "楼宇", "展览馆", "学校", "培训机构", "博物馆", "农林牧渔基地", "产业园区", "交通地名"],
    "公共设施": ["公共厕所"],
    "交通设施服务": ["公交车站", "停车场", "地铁站", "长途汽车站", "火车站"],
    "公司企业": ["公司", "公司企业", "工厂", "农林牧渔基地", "家居建材市场", "专卖店", "政府机关", "知名企业", "电讯营业厅", "传媒机构", "家电电子卖场", "产业园区", "花鸟鱼虫市场", "服装鞋帽皮具店", "休闲场所", "物流速递", "宾馆酒店", "住宅区", "人才市场", "交通车辆管理"],
    "购物": ["超级市场", "商场", "便民商店/便利店", "专卖店", "楼宇", "综合市场", "家居建材市场", "特色商业街", "服装鞋帽皮具店", "家电电子卖场"],
    "金融保险服务": ["自动提款机", "金融保险服务机构", "银行", "保险公司", "证券公司", "银行相关", "公司", "财务公司", "社会团体", "生活服务场所", "维修站点", "楼宇", "政府机关", "家居建材市场", "公司企业", "交通车辆管理"],
    "科教文化服务": ["培训机构", "学校", "科教文化场所", "科研机构", "传媒机构", "图书馆", "会展中心", "展览馆", "驾校", "文化宫", "美术馆", "文艺团体", "博物馆", "档案馆", "专卖店", "科技馆", "公司", "运动场馆", "政府机关", "美容美发店"],
    "商务住宅": ["住宅区", "楼宇", "产业园区", "商务住宅相关", "交通地名", "普通地名", "学校", "政府机关", "公司", "宾馆酒店", "商场", "中餐厅", "科研机构", "特色商业街", "物流速递", "旅馆招待所", "度假疗养场所", "展览馆", "住宿服务相关", "专卖店"],
    "生活服务": ["美容美发店", "维修站点", "摄影冲印店", "电讯营业厅", "洗衣店", "邮局", "家电电子卖场", "搬家公司", "专卖店", "服装鞋帽皮具店", "洗浴推拿场所", "个人用品/化妆品店", "公司", "运动场馆", "家居建材市场", "培训机构", "花鸟鱼虫市场", "摩托车维修", "娱乐场所", "便民商店/便利店"],
    "体育休闲服务": ["娱乐场所", "运动场馆", "休闲场所", "体育休闲服务场所", "度假疗养场所", "影剧院", "高尔夫相关", "中餐厅", "宾馆酒店", "外国餐厅", "住宅区", "中介机构", "学校", "农林牧渔基地", "茶艺馆", "洗浴推拿场所", "服装鞋帽皮具店", "家电电子卖场", "公园广场", "体育用品店"],
    "医疗保健服务": ["医药保健销售店", "医疗保健服务场所", "综合医院", "诊所", "专科医院", "动物医疗场所", "疾病预防机构", "急救中心"],
    "政府机构及社会团体": ["政府机关", "公检法机构", "社会团体", "政府及社会团体相关", "交通车辆管理", "工商税务机构", "民主党派", "外国机构", "公司", "科研机构", "度假疗养场所", "学校", "银行相关", "普通地名", "彩票彩券销售点", "农林牧渔基地", "公园广场", "住宅区", "休闲场所", "产业园区"],
    "住宿服务": ["宾馆酒店", "住宿服务相关", "旅馆招待所", "中餐厅", "住宅区", "洗浴推拿场所", "休闲场所", "科教文化场所", "楼宇", "旅行社", "度假疗养场所", "娱乐场所", "中介机构"]
};

export const poiSubcategoryLabels: Record<string, string> = {
    "中餐厅": "Chinese Restaurants",
    "快餐厅": "Fast Food",
    "外国餐厅": "Foreign Restaurants",
    "休闲餐饮场所": "Casual Dining",
    "宾馆酒店": "Hotels",
    "娱乐场所": "Entertainment Venues",
    "糕饼店": "Bakery & Pastry Shops",
    "咖啡厅": "Cafes",
    "休闲场所": "Leisure Venues",
    "茶艺馆": "Tea Houses",
    "冷饮店": "Cold Drink Shops",
    "综合市场": "General Markets",
    "旅馆招待所": "Inns & Guesthouses",
    "美容美发店": "Beauty & Hair Salons",
    "甜品店": "Dessert Shops",
    "楼宇": "Buildings",
    "服装鞋帽皮具店": "Apparel, Shoes & Leather Shops",
    "度假疗养场所": "Resorts & Sanatoriums",
    "风景名胜": "Scenic Spots",
    "运动场馆": "Sports Venues",
    "公园广场": "Parks & Squares",
    "风景名胜相关": "Scenic Spot Related",
    "普通地名": "Place Names",
    "住宅区": "Residential Communities",
    "科教文化场所": "Science, Education & Culture Venues",
    "科技馆": "Science Museums",
    "社会团体": "Social Organizations",
    "展览馆": "Exhibition Halls",
    "学校": "Schools",
    "培训机构": "Training Institutions",
    "博物馆": "Museums",
    "农林牧渔基地": "Agriculture, Forestry, Animal Husbandry & Fishery Bases",
    "产业园区": "Industrial Parks",
    "交通地名": "Transport Place Names",
    "公共厕所": "Public Toilets",
    "公交车站": "Bus Stops",
    "停车场": "Parking Lots",
    "地铁站": "Metro Stations",
    "长途汽车站": "Coach Stations",
    "火车站": "Railway Stations",
    "公司": "Companies",
    "公司企业": "Companies & Enterprises",
    "工厂": "Factories",
    "家居建材市场": "Home & Building Material Markets",
    "专卖店": "Specialty Stores",
    "政府机关": "Government Offices",
    "知名企业": "Well-known Enterprises",
    "电讯营业厅": "Telecom Service Halls",
    "传媒机构": "Media Organizations",
    "家电电子卖场": "Appliance & Electronics Stores",
    "花鸟鱼虫市场": "Flower, Bird, Fish & Pet Markets",
    "物流速递": "Logistics & Express Delivery",
    "人才市场": "Talent Markets",
    "交通车辆管理": "Traffic & Vehicle Administration",
    "超级市场": "Supermarkets",
    "商场": "Shopping Malls",
    "便民商店/便利店": "Convenience Stores",
    "特色商业街": "Specialty Commercial Streets",
    "自动提款机": "ATMs",
    "金融保险服务机构": "Finance & Insurance Institutions",
    "银行": "Banks",
    "保险公司": "Insurance Companies",
    "证券公司": "Securities Companies",
    "银行相关": "Bank Related",
    "财务公司": "Finance Companies",
    "生活服务场所": "Daily Service Venues",
    "维修站点": "Repair Sites",
    "科研机构": "Research Institutions",
    "图书馆": "Libraries",
    "会展中心": "Convention & Exhibition Centers",
    "驾校": "Driving Schools",
    "文化宫": "Cultural Palaces",
    "美术馆": "Art Museums",
    "文艺团体": "Arts Organizations",
    "档案馆": "Archives",
    "商务住宅相关": "Business & Residential Related",
    "住宿服务相关": "Accommodation Related",
    "摄影冲印店": "Photo Processing Shops",
    "洗衣店": "Laundry Services",
    "邮局": "Post Offices",
    "搬家公司": "Moving Companies",
    "洗浴推拿场所": "Bath & Massage Venues",
    "个人用品/化妆品店": "Personal Care & Cosmetics Shops",
    "摩托车维修": "Motorcycle Repair",
    "体育休闲服务场所": "Sports & Leisure Venues",
    "影剧院": "Theaters & Cinemas",
    "高尔夫相关": "Golf Related",
    "中介机构": "Agencies",
    "体育用品店": "Sporting Goods Stores",
    "医药保健销售店": "Pharmacy & Healthcare Stores",
    "医疗保健服务场所": "Healthcare Service Venues",
    "综合医院": "General Hospitals",
    "诊所": "Clinics",
    "专科医院": "Specialty Hospitals",
    "动物医疗场所": "Veterinary Clinics",
    "疾病预防机构": "Disease Prevention Institutions",
    "急救中心": "Emergency Centers",
    "公检法机构": "Public Security, Procuratorate & Court Offices",
    "政府及社会团体相关": "Government & Organization Related",
    "工商税务机构": "Industry, Commerce & Tax Offices",
    "民主党派": "Democratic Party Organizations",
    "外国机构": "Foreign Institutions",
    "彩票彩券销售点": "Lottery Outlets",
    "旅行社": "Travel Agencies"
};

export const functionTypes = ["商业消费", "居住生活", "教育文化", "医疗健康", "交通设施", "休闲游憩", "公共管理", "商务就业"];

export const functionTypeLabels: Record<string, string> = {
    "商业消费": "Commercial Consumption",
    "居住生活": "Residential Services",
    "教育文化": "Education & Culture",
    "医疗健康": "Healthcare",
    "交通设施": "Transport Facilities",
    "休闲游憩": "Leisure & Recreation",
    "公共管理": "Public Administration",
    "商务就业": "Business & Employment"
};

export const functionZoneLabels: Record<string, string> = {
    "商业消费功能区": "Commercial Consumption Zone",
    "居住生活功能区": "Residential Services Zone",
    "教育文化功能区": "Education & Culture Zone",
    "医疗健康功能区": "Healthcare Zone",
    "交通设施功能区": "Transport Facilities Zone",
    "休闲游憩功能区": "Leisure & Recreation Zone",
    "公共管理功能区": "Public Administration Zone",
    "商务就业功能区": "Business & Employment Zone",
    "综合功能区": "Mixed-use Zone",
    "低样本区": "Low-sample Area"
};

export const densityLevelLabels: Record<string, string> = {
    "高": "High",
    "中": "Medium",
    "低": "Low"
};

export const fieldLabels: Record<string, string> = {
    poi_id: "POI ID",
    name: "Name",
    category_l1: "Primary Category",
    category_l2: "Secondary Category",
    function_type: "Urban Function",
    address: "Address",
    district: "District",
    longitude: "Longitude",
    latitude: "Latitude",
    adcode: "Adcode",
    cellId: "Grid ID",
    count: "Count",
    poiCount: "POI Count",
    density: "Density",
    densityLevel: "Density Level",
    centerLongitude: "Longitude",
    centerLatitude: "Latitude",
    mixedDegree: "Mixed-use Degree",
    dominantFunction: "Dominant Function",
    functionZone: "Functional Zone",
    clusterId: "Cluster ID",
    rank: "Rank",
    clusterCount: "Cluster Size",
    clusterType: "Cluster Type"
};

export const valueLabels: Record<string, Record<string, string>> = {
    district: districtLabels,
    category_l1: poiCategoryLabels,
    category_l2: poiSubcategoryLabels,
    function_type: functionTypeLabels,
    dominantFunction: functionTypeLabels,
    functionZone: functionZoneLabels,
    densityLevel: densityLevelLabels
};
